title: Sunny's Blog
author: Sunny
email: tyyan14@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.

# social links
twitter_username: Tianyang Yan
github_username: sunnyty9

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
